### PR TITLE
SOC-1551 | Contributors count will be broken when we reach 1k contributors

### PR DESCRIPTION
**Pull request by rafalkalinski**
SOC-1551 | Contributors count will be broken when we reach 1k contributors

https://wikia-inc.atlassian.net/browse/SOC-1551

### CODE REVIEW

**Comment by kvas-damian** [comment]
Can we apply the same logic for post details view?

**Comment by rafalkalinski** [comment]
This is the same component

**Comment by bkoval** [comment]
LGTM :+1:

**Comment by kvas-damian** [comment]
LGTM

**Pull request merged**
