### PR TITLE
XW-171 load categories and sections under root not main page route

### PR DESCRIPTION
**Pull request by bognix**

### CODE REVIEW

**Comment by vforge** [comment]
LGTM

**Comment by kenkouot** [comment]
Code looks fine but do not merge this without clarification from @tedgill re: SEO impact! Thanks guys!

**Comment by bognix** [comment]
@kenkouot are you referring to https://wikia-inc.atlassian.net/browse/XW-213? If yes then this PR is not changing anything because neither /wiki/Main_Page/main/section/Foo (URL before the change) nor /main/section/Foo (URL after change) don't exist on Oasis

**Comment by hakubo** [comment]
LGTM

**Pull request merged**
