### PR TITLE
i18n-update | bulked translations downloaded from Crowdin

### PR DESCRIPTION
**Pull request by Warkot**
I downloaded new translations from Crowdin and they concern more then one feature, therefore this PR, which incorporates them all.

### CODE REVIEW

**Comment by rogatty** [comment]
Where do we use `wikia-top-contributors-label`? IIRC we currently use only the `article-top-contributors-label` and if you remove it then all non-english wikis will fallback to english. Are you sure you want to do that?

**Comment by Warkot** [comment]
Yes, I'm sure. It's incorrect for all languages.

**Comment by Warkot** [comment]
We have to invalidate the translations by removing the key `article-top-contributors-label`. If it's not removed as it was before, anyone who upload a Crowdin config file with `-t` will mark the faulty translations are OK ones.

**Comment by rogatty** [comment]
Is there somebody who made the decision that english fallback is better than incorrect label? Yeah, I've seen https://wikia-inc.atlassian.net/browse/CONCF-300 but I don't see anyone saying that.

**Comment by Warkot** [comment]
In my humble opinion, it's better. I found the root cause why the thing wasn't able to update, fixed it, but we don't need to merge it right now.

**Comment by rogatty** [comment]
Ok, so that's you who made the decision, don't be shy ;)
LGTM but I'd confirm with someone else too.

Also I think that we should remove `wikia-top-contributors-label` at all. It's not being used anywhere.

**Comment by Warkot** [comment]
It would be a pity to throw out so many good translations. :cry: But on the other hand, it's possible to pull them back from git/github histrory.

**Comment by hakubo** [comment]
Have you already uploaded the change to crowdin?
If yes lets wait a day or two for major languages at least

also please create a ticket for thing like this also

**Comment by Warkot** [comment]
I uploaded the changes to Crowdin.
I reopened and commented on [CONCF-300](https://wikia-inc.atlassian.net/browse/CONCF-300).
I created [LOC-66](https://wikia-inc.atlassian.net/browse/LOC-66).

**Comment by kvas-damian** [comment]
LGTM

**Pull request merged**
