### PR TITLE
SOC-2002 | Adding discussions assets

### PR DESCRIPTION
**Pull request by Bloodmoon24**
## Links

* https://wikia-inc.atlassian.net/browse/SOC-2002

## Description

Enabled discussions from ticket description, added provided assets (hero image, community badge).

## Reviewers

@bkoval @rafalkalinski

### CODE REVIEW

**Comment by rogatty** [comment]
When do we plan to do it properly? The first thing that comes to my mind is uploading these assets somewhere to DFS and returning URLs with wiki variables.

We shouldn't keep so many big images in this repo.

**Comment by bkoval** [comment]
@rogatty There's nothing like this in our backlog for the upcoming sprints. If you feel like this affects performance / comfort of development in Mercury, please file an issue in the SOC project and we'll prioritize it.

That said, we did discuss creating a possibility to store these in the static assets service some time ago (along with adding some creation tools for admins) but there's a different product work that is more important to our team's goals for now.

**Comment by bkoval** [comment]
LGTM :jack_o_lantern:

**Comment by rafalkalinski** [comment]
LGTM

**Pull request merged**
