### PR TITLE
SOC-1015 Unifying "close" button on Auth pages with the main Mercury app

### PR DESCRIPTION
**Pull request by bkoval**
https://wikia-inc.atlassian.net/browse/SOC-1015
@kvas-damian @rogatty @vforge @lizlux @rafalkalinski 

This pull request does two things:

1) Splits svg's into two folders (/common for svgs shared between apps and /main for svg used only in the main app) - this makes svgs build into two separate files (both are fetched into ember-main.hbs)

2) Makes "close" button on auth pages styled in the same way as a corresponding button in Mercury modals

### CODE REVIEW

**Comment by rogatty** [comment]
No need for additional task? Nice :)
LGTM

**Comment by vforge** [comment]
LGTM

**Comment by rafalkalinski** [comment]
LGTM

**Comment by kvas-damian** [comment]
LGTM

**Pull request merged**
