### PR TITLE
Bump vignette-js version

### PR DESCRIPTION
**Pull request by RafalWilinski**
Vignette-js lib is now supporting UUID-based URLs
https://github.com/Wikia/vignette-js/pull/26 & https://github.com/Wikia/vignette-js/pull/27

### CODE REVIEW

**Comment by RafalWilinski** [comment]
Tested on dedicated sandbox, looks ok.

**Comment by vforge** [comment]
LGTM

**Comment by RafalWilinski** [comment]
Not so LGTM, some links are broken now, for example article contributors.

http://static.wikia.nocookie.net/6c70a28f-1626-48ff-9178-48d5d12b759c/scale-to-width-down/100/fixed-aspect-ratio/width/100/height/100 - suffix added two times

**Comment by RafalWilinski** [comment]
Fix proposal: https://github.com/Wikia/vignette-js/pull/28

**Comment by RafalWilinski** [comment]
After testing on sandbox it seems that vignette-js 2.2.1 solves that problem. Waiting for vignette-js approval & release, then this.

**Comment by rogatty** [comment]
LGTM

**Pull request merged**
