### PR TITLE
use const {...} = Ember;

### PR DESCRIPTION
**Pull request by hakubo**
This is a pattern that I have noticed core team Ember members are using.

For some reason you can't do 
`import {Component} from 'ember`;
just yet

but we can achieve that with
```
import Ember from 'ember';
const {Component} = Ember;
```

I'd like to propose that we use this pattern in our code to make code more succinct and readable.

@rogatty @kvas-damian @adamkarminski @dianafa @bkoval

### CODE REVIEW

**Comment by rogatty** [comment]
LGTM

**Comment by bkoval** [comment]
Do we have a place in the guidelines repo to add this rule?

**Comment by gabrys** [comment]
What sort of magic is that?

**Comment by hakubo** [comment]
Object destructuring
https://babeljs.io/docs/learn-es2015/#destructuring

**Comment by vforge** [comment]
@gabrys JavaScript of the future ;)

LGTM

**Comment by bognix** [comment]
@hakubo - can we merge it?

**Comment by hakubo** [comment]
@bognix yes - next part would be to figure out if we want to do that for all files
or it would happen over time 
and 
put that in our guidelines (I'll do that)

thanks!

**Pull request merged**
