### PR TITLE
SOC-1089 Renaming zh-tw to zh in mercury repository

### PR DESCRIPTION
**Pull request by bkoval**
https://wikia-inc.atlassian.net/browse/SOC-1089

@kenkouot @lizlux @Warkot @kvas-damian Please, let me know if this change won't break anything for your teams.

### CODE REVIEW

**Comment by kvas-damian** [comment]
@Grunny Don't we need to update crowdin scripts to match this change?

**Comment by Warkot** [comment]
LGTM, but be aware that Crowdin outputs the files in the `lang-variant` format, so they have to be altered manually after each project build→download→update.

**Comment by kenkouot** [comment]
Don't think this will affect anything on HG core end atm so LGTM

**Comment by Grunny** [comment]
@kvas-damian @Warkot we can probably just setup aliasing for mercury for `zh-TW` -> `zh` in the crowdin tools, so you don't need to modify it, as we do for MediaWiki and iOS, or you can do this in the crowdin.conf files using something like:
```
export.zh-TW = "${export.base}/zh/"
```

**Comment by kvas-damian** [comment]
thanks @Grunny it works. Update for config here: https://github.com/Wikia/mercury/pull/1136

**Pull request merged**
