### PR TITLE
XW-121 | Used fixed version of dependencies

### PR DESCRIPTION
**Pull request by bognix**
PR to release: https://github.com/Wikia/mercury/pull/1800

### CODE REVIEW

**Comment by tomasznapieralski** [comment]
LGTM :+1:

**Comment by rogatty** [comment]
LGTM

**Comment by hakubo** [comment]
LGTM - it would be cool to automate checking it, so we don't add back again ~ by accident

**Comment by hakubo** [comment]
hmm that should work: `cat package.json | jq '.devDependencies[]' -Mr | grep '[x\^~]' > /dev/null`
:)

**Comment by bognix** [comment]
@hakubo - not exactly, it would fail if we have something like Wikia/x#v2.0.0 (because you are testing against "x" presence

**Pull request merged**
