### PR TITLE
SOC-1781 | Updating the Star Wars discussions badge

### PR DESCRIPTION
**Pull request by bkoval**
@kvas-damian @Bloodmoon24 
https://wikia-inc.atlassian.net/browse/SOC-1781

### CODE REVIEW

**Comment by Bloodmoon24** [comment]
LGTM

**Comment by kvas-damian** [comment]
Ticket says. Only for EN starwars ;)

**Comment by bkoval** [comment]
@kvas-damian allright, allright, changed it ;>

**Comment by kvas-damian** [comment]
LGTM

**Pull request merged**
