### PR TITLE
DAT-3543 | remove margin around icon image

### PR DESCRIPTION
**Pull request by dianafa**
https://wikia-inc.atlassian.net/browse/DAT-3543

### CODE REVIEW

**Comment by rogatty** [comment]
@dianafa @rybmat will this fix https://wikia-inc.atlassian.net/browse/XW-776? If yes, please close the ticket after this is merged :)

**Comment by dianafa** [comment]
@rogatty issue with images in lists will be fixed only partially- for icons. For normal size images problem will remain.

**Comment by SebastianMarzjan** [comment]
Let is :snowflake:

**Comment by tomasznapieralski** [comment]
LGTM

**Pull request merged**
