### PR TITLE
Remove 100% GA account

### PR DESCRIPTION
**Pull request by rogatty**
https://wikia-inc.atlassian.net/browse/CONCF-410

### CODE REVIEW

**Comment by Warkot** [comment]
LGTM :shipit:

**Comment by rogatty** [comment]
ping @hakubo

**Comment by hakubo** [comment]
unfortunately we have to also update GoogleAnalytics.ts
for example:
https://github.com/Wikia/mercury/blob/dev/front/scripts/mercury/modules/Trackers/GoogleAnalytics.ts#L45

**Comment by rogatty** [comment]
@hakubo well, we didn't _have to_ because we have clever conditions like
`if (this.accounts[this.accountSpecial])` :)

But seriously - thanks for noticing, I've cleaned it up.

**Comment by hakubo** [comment]
LGTM

**Comment by tomasznapieralski** [comment]
LGTM

**Pull request merged**
