### PR TITLE
INT-66: Display loading indicator when saving section edit

### PR DESCRIPTION
**Pull request by inez**
This change is also cleaning up application.hbs template to have LoadingSpinnerComponent called out only once.

### CODE REVIEW

**Comment by rogatty** [comment]
LGTM but remember to test if loading spinner is still working for regular article transitions.

**Comment by hakubo** [comment]
LgTM

**Comment by rogatty** [comment]
Tests are failing because:
`front/scripts/main/routes/EditRoute.ts(13,24): 2339 Property 'then' does not exist on type 'Transition'.`

**Comment by inez** [comment]
@rogatty Tests are failing because of not related problem and not ever introduced within this PR, so I'm going to go ahead and merge it. Problem with tests is separately addressed in https://github.com/Wikia/mercury/pull/785

**Pull request merged**
