### PR TITLE
Hg 753 - Adding ability to load first article async

### PR DESCRIPTION
**Pull request by lizlux**
This article does a few things:
* Adds the ability to toggle between loading article content in the page source and asynchronously
* Implements loading all article content in the page source when `?_escaped_fragment_=` is present in the URL
* Includes the appropriate meta tag in the page source when article content is loaded asynchronously

Note that this PR assumes we'll be enabling async article loading on a per-wiki basis. Once https://wikia-inc.atlassian.net/browse/HG-755 is figured out we can modify that scheme.

### CODE REVIEW

**Comment by kenkouot** [comment]
lgtm outside of conflict

**Comment by rogatty** [comment]
@lizlux is this the expected behaviour? It looks odd. Previously we were overlaying spinner over the content and now we render it into application.hbs `{{outlet}}`.

>After transitioning into a loading substate, the corresponding template for that substate, if present, will be rendered into the main outlet of the parent route, e.g. foo.bar.loading's template would render into foo.bar's outlet. (This isn't particular to loading routes; all routes behave this way by default.)

from http://guides.emberjs.com/v1.12.0/routing/loading-and-error-substates/

**Comment by lizlux** [comment]
@rogatty I was hoping to fix the fact that before the first article loads, if we're loading it asynchronously, there's no loading spinner. That will have to wait for a different ticket though, as this ticket was not specifically for that. You're implementation is fine for now. Thanks!

**Comment by kenkouot** [comment]
This looks good but please don't merge yet as it will interfere with some tests we have planned.

**Comment by lizlux** [comment]
Checked with @kenkouot, it's fine to merge while tests are in progress.

**Pull request merged**
