### PR TITLE
add .npmrc with save-exact=true

### PR DESCRIPTION
**Pull request by hakubo**
## Links

* https://docs.npmjs.com/misc/config#save-exact
* https://gist.github.com/kentcdodds/5352dcce1c62630fe9d0#file-npmrc

## Description

We use exact versions in our package.json. I always forget about that - that will do that for us automatically

## Reviewers

@Wikia/x-wing

### CODE REVIEW

**Comment by rogatty** [comment]
LGTM

**Comment by vforge** [comment]
:+1:

**Comment by tomasznapieralski** [comment]
LGTM

**Comment by Warkot** [comment]
:+1: LGTM

**Pull request merged**
