### PR TITLE
Replace ApplicationView with ApplicationWrapperComponent

### PR DESCRIPTION
**Pull request by rogatty**
Because views are deprecated in Ember 1.13 I've refactored `ApplicationView` into `ApplicationWrapperComponent`.

**Don't merge, this is work in progress.**

To do:
Figure out how to handle passing query params between layers and allow their modification from component.

### CODE REVIEW

**Comment by kenkouot** [comment]
I merged https://github.com/Wikia/mercury/pull/1140, can you make sure this works with that?

**Comment by dianafa** [comment]
can we close this PR?

**Comment by rogatty** [comment]
@dianafa let's wait few more days as X-Wing will work on it in the current sprint (starting today, see XW-343) and it might be useful as a reference.

**Comment by rogatty** [comment]
New PR: https://github.com/Wikia/mercury/pull/1429

**Pull request closed without merging**
