### PR TITLE
Cleaning up inline svg logo

### PR DESCRIPTION
**Pull request by bkoval**
This cleans up unnecessary stuff from the inliner.

### CODE REVIEW

**Comment by hakubo** [comment]
LGTM

**Comment by Warkot** [comment]
I feel that this one still contains some bloat. You could use an already existing logo in app repo here: https://github.com/Wikia/app/blob/dev/extensions/wikia/WikiaLogo/images/wikia_logo_white.svg? It has just 1 kB in comparison to the 2.1 kB of this one (not encoded).
Or you could use this—I optimized the one from this PR by aditional manual editing:
```
<svg xmlns="http://www.w3.org/2000/svg" height="41px" width="145px" version="1.1">
	<g fill-rule="evenodd" fill="#fff">
		<path d="m95 13.7h-12.6l-5 6-2.4 2.9v-21.9h-8.7v39.1h8.7v-7l3.1-2.9 5.9 9.9h11.4l-10.9-15.8 10.5-10.3"/>
		<path d="m31.3 31.5l-4.4-17.8h-10.1l-4.2 17.8-3.4-17.8h-9.1l6.8 26.1h11.7l3.3-13.5 3.3 13.5h11.8l6.8-26.1h-9.2l-3.3 17.8"/>
		<path d="m144.2 21.3l0.5-7.6h-8l-0.6 2.9c-1.8-2-4.1-3.6-8.2-3.6-7.3 0-11.3 4.7-11.3 13.7s4 13.7 11.3 13.7c4.1 0 6.4-1.6 8.2-3.6l0.6 3h8l-0.5-7.7v-10.8zm-8.7 8.7c-1.2 1.5-2.9 2.5-5.2 2.5-2.6 0-4.7-1.8-4.7-5.8s2.1-5.7 4.7-5.7c2.3 0 4.1 0.9 5.2 2.4v6.6z"/>
		<path d="m53.1 10.9c2.8 0 5.1-2.3 5.1-5 0-2.8-2.2-5.1-5-5.1s-5 2.3-5 5.1c-0.1 2.7 2.2 5 5 5"/>
		<path d="m48.1 13.7v26.1h12.6v-5.5h-3.9v-15.1h3.9v-5.5h-12.6"/>
		<path d="m107.2 0.8c-2.8 0-5 2.3-5 5.1 0 2.7 2.3 5 5 5 2.8 0 5.1-2.3 5.1-5-0.1-2.8-2.3-5.1-5.1-5.1"/>
		<path d="m99.6 13.7v5.5h4v15.1h-4v5.5h12.6v-26.1h-12.6"/>
	</g>
</svg>
```
It is even smaller than 1 kB. Moreover you could remove tabs and newlines before url-encoding it.

**Comment by Warkot** [comment]
And BTW, have you gave it a thought to put it into a CSS class to make it cache-friendly?

**Comment by bkoval** [comment]
I removed inlined SVG from HTML, we'll consider automating of inlining SVG's into html here -> 
https://wikia-inc.atlassian.net/browse/SOC-545 There's also https://wikia-inc.atlassian.net/browse/HG-588 as SVG's in svg/ and svg/images are also not fully optimized (at least not all of them).

As for caching, login / signup flow consists exclusively of static pages, so HTML should be cacheable as well and using  tag for an image makes more semantic sense :dancer:

**Comment by Warkot** [comment]
Thanks for the comprehensive reply with the ticket links! LGTM :shipit:

**Comment by lizlux** [comment]
LGTM

**Pull request merged**
