### PR TITLE
Removing unneeded comma

### PR DESCRIPTION
**Pull request by bkoval**
Anyone? :)

### CODE REVIEW

**Comment by vforge** [comment]
Rejected - AFAIK Removing that comma is not needed. Pinging @hakubo for more info.

**Comment by rogatty** [comment]
LGTM

**Comment by hakubo** [comment]
this comma is not bad, commas at the and help with ordering properties and having smaller PR
we don't have that in our guide lines yet I think

Will add it later

**Comment by bkoval** [comment]
:+1:

**Pull request closed without merging**
