### PR TITLE
XW-1112 | smart banner image scaling

### PR DESCRIPTION
**Pull request by Warkot**
## Links

* http://wikia-inc.atlassian.net/browse/XW-1112

## Description

Smart banner image was loaded as a huge original image. Now it's just a tiny thumbnail.

## Reviewers

@Wikia/x-wing

### CODE REVIEW

**Comment by hakubo** [comment]
LGTM

**Comment by rogatty** [comment]
What happens when there is no icon? Or maybe there is always _some_ icon?
If it works fine then LGTM.

**Comment by vforge** [comment]
LGTM

**Comment by Warkot** [comment]
@rogatty, this https://github.com/Wikia/mercury/pull/2139/files#diff-4c2bd35b669f00708f925da69e1936e6R23 makes the icon div hidden when there's no icon. Nevertheless, I added https://github.com/Wikia/mercury/commit/275b9687da46bb2a4097731a0a5b85da947075a4 to omit the style attribute at all when there's no icon—as this function was returning `background-image: url(undefined)`.

**Comment by rogatty** [comment]
LGTM

**Pull request merged**
