### PR TITLE
SOC-2107 | Make default badge not transparent

### PR DESCRIPTION
**Pull request by bkoval**
## Links

* http://wikia-inc.atlassian.net/browse/SOC-2107

## Reviewers

@Bloodmoon24 @rafalkalinski

### CODE REVIEW

**Comment by kvas-damian** [comment]
Why we don't reuse svg that is already loaded as a symbol on every page?

**Comment by bkoval** [comment]
@kvas-damian Better? :)

**Comment by Bloodmoon24** [comment]
LGTM

**Comment by kvas-damian** [comment]
much better. Thanks @bkoval  :bow:

**Comment by rafalkalinski** [comment]
LGTM

**Comment by hakubo** [comment]
lgtm

**Pull request merged**
