### PR TITLE
Enable Optimizely

### PR DESCRIPTION
**Pull request by mklucsarits**
We don't yet have a hot-swappable configuration tool in place, and we need to enable Optimizely this week for an experiment that was expected to run two weeks ago, so this seems like the only thing to do. Alternative suggestions to enable this on production are welcome.

This change will result in the Optimizely JS snippet being loaded for every Mercury user.

### CODE REVIEW

**Comment by hakubo** [comment]
this could come from process.env.optimizely or something like that and
or we could use consul to store such configuration

**Comment by kenkouot** [comment]
merge dev into branch to fix build error

**Comment by mklucsarits** [comment]
Changed to use env flag.

**Comment by mklucsarits** [comment]
I need to get this on production on Friday, so please take a look at it before I merge.

**Comment by kenkouot** [comment]
LGTM

**Pull request merged**
