### PR TITLE
XW-1112 | fix ellipsis in (Android) smart banner

### PR DESCRIPTION
**Pull request by Warkot**
## Links

* http://wikia-inc.atlassian.net/browse/XW-1112

## Description

Ellipsis was broken in smart banner. Could be seen on Android phones on e.g. http://wowwiki.wikia.com at 360 × 640 resolution.

## Reviewers

@Wikia/x-wing

### CODE REVIEW

**Comment by vforge** [comment]
:+1:

**Comment by rogatty** [comment]
Thanks! LGTM

**Comment by tomasznapieralski** [comment]
:+1:

**Comment by hakubo** [comment]
lgtm

**Pull request merged**
