### PR TITLE
XW-343 Stop using Ember.View

### PR DESCRIPTION
**Pull request by rogatty**
https://wikia-inc.atlassian.net/browse/XW-343

https://github.com/Wikia/mercury/pull/1402 was borked, this is proper PR.

### CODE REVIEW

**Comment by vforge** [comment]
LGTM

**Comment by bognix** [comment]
LGTM

**Comment by bognix** [comment]
please resolve merge conflicts before we can move it to QA

**Comment by tomasznapieralski** [comment]
LGTM

**Pull request merged**
