### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by hakubo**
Tests are passing locally
Server boots up and serves pages

Please run all our tests

### CODE REVIEW

**Comment by hakubo** [comment]
@Warkot @vforge

**Comment by vforge** [comment]
Version bump :+1:

LGTM

**Comment by Warkot** [comment]
Seems to be fine. All tests passed (even twice :smile:). Server works. However there were around 35 `WARNs` from `npm` about version of the node: `npm WARN engine hapi@8.4.0: wanted: {"node":">=0.10.32"} (current: {"node":"v0.10.25","npm":"1.3.10"})`.

**Comment by rogatty** [comment]
Karma is failing:

```
TypeError: 'undefined' is not an object (evaluating 'M.prop')
  at /var/lib/jenkins/workspace/Mercury-Front/test/helpers/baseline.js:9



/var/lib/jenkins/workspace/Mercury-Front/gulp/tasks/karma.js:33
		throw new Error(error);
		      ^
Error: Error in plugin 'gulp-karma'
karma exited with code 1
```

**Comment by rogatty** [comment]
Tests are somehow broken by glob v5.0.3. Instead of resolving multiple conflicts I'm gonna close this and create new branch + PR.

**Pull request closed without merging**
