### PR TITLE
SOC-1809 | fix for opening reply editor in iOS browsers

### PR DESCRIPTION
**Pull request by rafalkalinski**
https://wikia-inc.atlassian.net/browse/SOC-1809

### CODE REVIEW

**Comment by rogatty** [comment]
I think it clashes with https://github.com/Wikia/mercury/commit/3541645e42981e7393c6de54274062e5f3d35d23

**Comment by bkoval** [comment]
Good point :cop:! How about we use SOC-1505-backup as a base branch to avoid conflicts? :)

**Comment by rafalkalinski** [comment]
I don't think is necessary right now. 
I will deal with conflicts either I use SOC-1505-backup or later when I merge with dev.
My changes were simple and I believe I can deal with the merge.

**Comment by bkoval** [comment]
LGTM

**Comment by kvas-damian** [comment]
LGTM

**Pull request merged**
