### PR TITLE
ADEN-3070 Change IVW3 tracking key

### PR DESCRIPTION
**Pull request by fraszczakszymon**
## Description

We need to track users when Ember is loaded. They show a survey for 0.5-1% of traffic and here are the changes which prevents Ember to override survey code if it was loaded earlier.

## Links

* http://wikia-inc.atlassian.net/browse/ADEN-3070
* http://wikia-inc.atlassian.net/browse/ADEN-3087

## Reviewers

@Wikia/adeng

### CODE REVIEW

**Comment by drets** [comment]
LGTM :+1:

**Comment by fraszczakszymon** [comment]
Pinging CR-duty guys: @hakubo @rogatty

**Comment by rogatty** [comment]
LGTM

**Comment by drets** [comment]
LGTM :+1:

**Pull request merged**
