### PR TITLE
CE-3427: Remove X button and hide banner after 7 sec

### PR DESCRIPTION
**Pull request by lukaszkonieczny**
Remove X button and hide banner after 7 sec

### CODE REVIEW

**Comment by lukaszkonieczny** [comment]
ping @Wikia/community-engineering @vforge (I don't know why I can't add @Wikia/x-wing)

**Comment by hakubo** [comment]
LGTM

**Comment by Grunny** [comment]
LGTM.

**Comment by rogatty** [comment]
@lukaszkonieczny we were a secret team :black_joker:! Should work now :)

**Comment by tomasznapieralski** [comment]
LGTM

**Pull request merged**
