### PR TITLE
Increment adLogicPageViewCounter on ads reload

### PR DESCRIPTION
**Pull request by rogatty**
https://wikia-inc.atlassian.net/browse/CONCF-72

app-side: https://github.com/Wikia/app/pull/6574

### CODE REVIEW

**Comment by hakubo** [comment]
LGTM

**Comment by rogatty** [comment]
Let's merge and deploy it after https://github.com/Wikia/app/pull/6574 is live.

**Comment by gabrys** [comment]
Thanks guys, Wikia/app#6574 is going to be a part of release-269 (to be released on March 18)

**Pull request merged**
