### PR TITLE
HG-657: Updated types definitions for Ember

### PR DESCRIPTION
**Pull request by inez**
Updated to version 1.11.3 even tought we are on 1.11.1 but still better than staying with way old way outdated version

### CODE REVIEW

**Comment by hakubo** [comment]
Awesome, thanks!

**Comment by rogatty** [comment]
Tests are failing with:
```
front/scripts/mercury/modules/Trackers/GoogleAnalytics.ts(24,15): 7006 Parameter 'domain' implicitly has an 'any' type.
```

This is an old code that doesn't cause problems when running tests on dev branch.
IMO this PR should include fix for it too. It's possible that there will be more errors related to typing.

**Comment by inez** [comment]
Ready for CR again

**Comment by hakubo** [comment]
LGTM

**Comment by rogatty** [comment]
LGTM

**Pull request merged**
