### PR TITLE
CONCF-80 | enable caching in Mercury

### PR DESCRIPTION
**Pull request by Warkot**

### CODE REVIEW

**Comment by mklucsarits** [comment]
This is not directly related to your change, but I don't understand why we have this same object in two different places. It goes against the DRY principle.

**Comment by Warkot** [comment]
They should probably have different names, as the one in `showArticle.ts` is for the first Mercury response and the one in `article.ts` is for the API responses. By the way, these sames aren't too descriptive.

**Comment by hakubo** [comment]
LGTM

**Comment by hakubo** [comment]
@Warkot is it still WIP than?

**Comment by Warkot** [comment]
I wasn't able to make it work on sandbox env, but I heard, it *should* be working on prod. Something also has to be done to the random article caching, but it might need another pull request/ticket/story. @bognix, what do you think?

**Comment by Warkot** [comment]
One `LGTM` from @hakubo, anyone is eager to give some more? @bognix @rogatty

**Comment by rogatty** [comment]
LGTM

**Comment by bognix** [comment]
LGTM

**Comment by kenkouot** [comment]
LGTM

**Comment by vforge** [comment]
LGTM

**Comment by rogatty** [comment]
:hand: **Don't merge before https://github.com/Wikia/app/pull/6892 hits production!** :hand:

**Comment by hakubo** [comment]
@Warkot mkay https://github.com/Wikia/app/pull/6892 has landed.
Should we release that tomorrow?

**Comment by Warkot** [comment]
@hakubo I've checked it today (well, yesterday) and I did it once again just now. We're running release-285 on production (http://www.wikia.com/Special:Version) and here https://github.com/Wikia/app/blob/release-285/extensions/wikia/MercuryApi/MercuryApiHooks.class.php#L89 you can see that there's only one URL purged. We probably have to wait until Tuesday. :snail:

**Comment by Warkot** [comment]
Branch merged, because it was already ported to the last release to prevent flooding Mecrury machines over the weekend—we are at 100% traffic at this point.

**Pull request merged**
