### PR TITLE
SOC-748 Add login statue of user to GA

### PR DESCRIPTION
**Pull request by jsutterfield**
Update the login state in GA from being hardcoded to 'anon' to actually check the login state of the user.

Ticket: https://wikia-inc.atlassian.net/browse/SOC-748

### CODE REVIEW

**Comment by hakubo** [comment]
LGTM

**Comment by mklucsarits** [comment]
LGTM

**Comment by mklucsarits** [comment]
The Mercury codebase is changing so fast. :horse_racing: Looks like this change is already outdated. GoogleAnalytics.ts has become UniversalAnalytics.ts, but also, the code changes here will need to reflect anon/logged-in state as well: https://github.com/Wikia/mercury/pull/826

**Comment by mklucsarits** [comment]
I'm closing this, and I'll open a new pull request targeted at the dev branch once I complete the remaining work for SOC-748.

**Pull request closed without merging**
