### PR TITLE
ADEN-2486 | Add Flite tag support for mercury

### PR DESCRIPTION
**Pull request by fraszczakszymon**
Make it possible to use `<flite>` tag in articles' content on mercury.

Related PR: https://github.com/Wikia/app/pull/8806

### CODE REVIEW

**Comment by nandy-andy** [comment]
Update the description, please :)

**Comment by nandy-andy** [comment]
LGTM :+1:

@bognix @rogatty @vforge do you guys wanna take a look? :smile_cat:

**Comment by vforge** [comment]
So basically that will load as many flite <scripts> as tags?

**Comment by nandy-andy** [comment]
That's correct @vforge! And it'll add as many `<script />` tags and `` tags as `<flite />` tags on a page. 

But keep in mind it's a "staff tool" and it's usually used as one per a page since our Community Development team puts a quiz on a page with the tag. Also, the `<script />` tag which is being added provides some data used later by the logic of `combo.js` script, so having one of it per page with many flite tags isn't that trivial, I'm afraid :disappointed:

**Comment by rogatty** [comment]
It's a shame we can't use some API instead of `<script>` tag attributes :(
Apart from that LGTM.

**Pull request merged**
