### PR TITLE
SOC-1572 | fixed a white box appearing behind the avatar when clicking in the top bar

### PR DESCRIPTION
**Pull request by katanka**

### CODE REVIEW

**Comment by bkoval** [comment]
LGTM :+1:

**Comment by rafalkalinski** [comment]
Please, make sure the tests are okay,
beside that LGTM

**Comment by rogatty** [comment]
`This branch is 1 commit ahead, 2316 commits behind dev.`
Probably this is the cause tests are failing.

**Comment by kvas-damian** [comment]
For future please add at least link to ticket.

**Pull request merged**
