### PR TITLE
Int 117

### PR DESCRIPTION
**Pull request by mari-mcmurtrie**
This is fix for 2 icons style. I changed icons in DOM tree so that this is no longer inside header section. Shorten a section header width to make space for icons in order to fit everything in 1 line.

### CODE REVIEW

**Comment by rogatty** [comment]
Are you sure this should be targeted at dev branch? It's 19 files and not "fix for 2 icons style" ;)

**Comment by mari-mcmurtrie** [comment]
I made this branch off INT-102, and made pull request from GitHub. It looks like this pull request is with respect to dev branch, that is why I have more changes, including all changes from INT-102. 
Maybe I messed up something? Anyways, the icon changes are the last 2 commits.

**Comment by mari-mcmurtrie** [comment]
@inez will you review this please?

**Comment by inez** [comment]
Yes

**Comment by inez** [comment]
This pr should be closed and new one should be created that targets int-102.

**Comment by inez** [comment]
Also, please avoid in commit messages things like "This should go to test now"

**Comment by mari-mcmurtrie** [comment]
Thanks for checking. I have bad pull request so I have to close this.

**Pull request closed without merging**
