### PR TITLE
ADEN-1885 Remove scroll depth

### PR DESCRIPTION
**Pull request by nandy-andy**
The experiment has finished. We wrapped up the results and we can remove the experimental code.

While working on scroll-depth I [did changes](https://github.com/Wikia/mercury/commit/90ecc3679f1352d9a873f6b6f87c3f80751a88b2) in `trachAds()` function. I kept them because it makes sense :japanese_ogre: 

ping @hakubo @kenkouot @rogatty @Warkot - guys it's your code, so I'd like you to take a look and know about the changes :smile_cat:

### CODE REVIEW

**Comment by rogatty** [comment]
LGTM

**Comment by Warkot** [comment]
LGTM :octocat:

**Comment by hakubo** [comment]
Looks good to me.

**Comment by tomasznapieralski** [comment]
LGTM

**Pull request merged**
