### PR TITLE
SOC-1371 Replace inline styling per flipcss recommendation

### PR DESCRIPTION
**Pull request by armonr**
/CC @bkoval @vforge 

https://wikia-inc.atlassian.net/browse/SOC-1371

### CODE REVIEW

**Comment by bkoval** [comment]
LGTM :dancers: 
1) Does this make the console warnings in Mercury dissapear?
2) Do you think it's worth it to create a QA ticket for this, just to be sure this implementation works well in all the browsers?

**Comment by armonr** [comment]
@bkoval: I verified absence of warnings on full service restart, and created [SOC-1371](https://wikia-inc.atlassian.net/browse/SOC-1371) as a followup. Thanks!

**Comment by bkoval** [comment]
Awesome!

**Comment by vforge** [comment]
Awesome, thanks!

**Pull request merged**
