### PR TITLE
XW-903 Add `vary: accept-encoding` header to all responses

### PR DESCRIPTION
**Pull request by rogatty**
https://wikia-inc.atlassian.net/browse/XW-903

### CODE REVIEW

**Comment by hakubo** [comment]
Lgtm

**Comment by vforge** [comment]
:+1:

**Comment by kvas-damian** [comment]
LGTM

**Comment by rogatty** [comment]
I've upgraded Hapi to v9.5.1 so we don't have `vary: cookie, accept-encoding, accept-encoding` (it was a Hapi bug). Couldn't upgrade to >9 because it requires Node v4.

**Comment by hakubo** [comment]
Lgtm.

**Pull request merged**
