### PR TITLE
SOC-992 Remove technical debt when Helios start setting cookie on registration

### PR DESCRIPTION
**Pull request by rafalkalinski**
https://wikia-inc.atlassian.net/browse/SOC-992

### CODE REVIEW

**Comment by rogatty** [comment]
```
PhantomJS 1.9.8 (Linux 0.0.0) ERROR
  Some of your tests did a full page reload!
```

**Comment by bkoval** [comment]
@rogatty For God sakes, we can read what Jenkins says! ;) :santa: :hocho: :8ball:

**Comment by bkoval** [comment]
LGTM

**Comment by garthwebb** [comment]
LGTM

**Pull request merged**
