### PR TITLE
INT-274 | Add padding between image and text on company overview page

### PR DESCRIPTION
**Pull request by perjg**
Padding is for desktop mode only.

https://wikia-inc.atlassian.net/browse/INT-274

### CODE REVIEW

**Comment by mari-mcmurtrie** [comment]
'em' is better?

**Comment by perjg** [comment]
@rogatty @hakubo I get a Linter failure for this PR.

In the log I just see:
```
+ npm run linter
npm ERR! Linux 3.19.0-30-generic
npm ERR! argv "node" "/usr/bin/npm" "run" "linter"
npm ERR! node v0.10.37
npm ERR! npm  v2.3.0

npm ERR! missing script: linter
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/lib/jenkins/workspace/Mercury-PR-Checks/JOB-483/npm-debug.log
```

**Comment by rogatty** [comment]
You probably have an old package.json. I wouldn't worry about that as there is only CSS change.

**Comment by hakubo** [comment]
just merge dev branch
also 
can we use rem directly ? :)

**Comment by perjg** [comment]
@hakubo Merging dev directly worked fine.
I changed to use rem directly too.

**Pull request merged**
