### PR TITLE
fix abtest module import by lowercasing its path

### PR DESCRIPTION
**Pull request by Warkot**
## Description

JS console was throwing this error:
```
Uncaught Error: Could not find module `common/modules/AbTest` imported from `main/components/feedback-form`
```

All filenames, paths and the imports have to be lowercase. Linux machines, on which our app works, are case sensitive.

## Reviewers

@Wikia/x-wing @adamkarminski @lukaszkonieczny @kamilkoterba

### CODE REVIEW

**Comment by rogatty** [comment]
LGTM

**Comment by kamilkoterba** [comment]
shouldn't we rename a file as well?

**Comment by Warkot** [comment]
@kamilkoterba The file was already renamed to lower-dashed-case [here](https://github.com/Wikia/mercury/commit/8f28181def9171a47af0e60ef715932572523fb0#diff-1297dbce62d932408cafcd59bbf94e39). The import path was new, it was added in parallel to that case-changing PR. This divergence caused a difference between the import path and the path of the actual file caused the issue.

**Comment by kamilkoterba** [comment]
Thanks, must have had outdated repo. That makes sense.

**Pull request merged**
