### PR TITLE
Add check for call-signature to tslint and fix existing signatures

### PR DESCRIPTION
**Pull request by rogatty**
I'm tired of writing comments like "Add :void". This will enforce correct typing with tslint.
See https://www.npmjs.com/package/tslint#supported-rules

/cc @hakubo @kenkouot

### CODE REVIEW

**Comment by hakubo** [comment]
very very nice,
Thanks
LGTM

**Comment by rogatty** [comment]
@kenkouot do you agree that we should enable this check?

**Comment by hakubo** [comment]
@lizlux do you agree that we should enable this check?

**Comment by lizlux** [comment]
LGTM. If we're going to have that rule it's great to be able to enforce it with TSLint. Thanks @rogatty!

**Comment by kenkouot** [comment]
Yeah this is good!

**Comment by rogatty** [comment]
This rule doesn't actually fail the tests, just displays warning. Still, better than nothing!

**Pull request merged**
