### PR TITLE
XW-395 | Remove deprecated /api/v1/* Mercury paths

### PR DESCRIPTION
**Pull request by Warkot**

### CODE REVIEW

**Comment by hakubo** [comment]
LGTM

**Comment by hakubo** [comment]
LGTM :rocket:

**Comment by Warkot** [comment]
So much LGTM, wow! Very thanks. :dog2: 
doge

**Comment by hakubo** [comment]
LGTM :dog:

**Comment by rogatty** [comment]
Can you also fix this comment? https://github.com/Wikia/mercury/blob/dev/server/routes.ts#L83
LGTM

**Comment by Warkot** [comment]
It was already fixed while adding the `/api/mercury/` routes, as you can see here → https://github.com/Wikia/mercury/blob/dev/server/routes.ts#L109 :smile: 
The comment you pointed to, @rogatty, is just removed, so this one stays →
https://github.com/Wikia/mercury/blob/XW-395/server/routes.ts#L82

**Comment by rogatty** [comment]
:see_no_evil:

**Pull request merged**
