### PR TITLE
XW-602 | Reset imageProperties before cropping image in Curated Content Editor

### PR DESCRIPTION
**Pull request by rogatty**
https://wikia-inc.atlassian.net/browse/XW-602

### CODE REVIEW

**Comment by vforge** [comment]
LGTM

**Comment by hakubo** [comment]
LGTM

**Comment by tomasznapieralski** [comment]
LGTM

**Comment by bognix** [comment]
LGTM, sooo much LGTM

**Comment by Warkot** [comment]
LGTM

**Pull request merged**
