### PR TITLE
CONCF-672 | enable caching for Curated Content

### PR DESCRIPTION
**Pull request by Warkot**
**DON'T MERGE**
https://github.com/Wikia/app/pull/7666 should be merged and push to production first.

:dog2:

### CODE REVIEW

**Comment by hakubo** [comment]
LGTM

**Comment by hakubo** [comment]
Since this https://github.com/Wikia/app/pull/7793 has been merged, should this one as well be merged?

**Comment by Warkot** [comment]
Should be tested first.

**Comment by Warkot** [comment]
Closing because of https://wikia-inc.atlassian.net/browse/XW-188.

**Pull request closed without merging**
