### PR TITLE
SOC-1967 | Remove inherited line-height from auth-footer-link

### PR DESCRIPTION
**Pull request by bkoval**
@rafalkalinski @katanka 
https://wikia-inc.atlassian.net/browse/SOC-1967

### CODE REVIEW

**Comment by katanka** [comment]
On desktop, it looks like the auth footer text has no top padding now.

**Comment by katanka** [comment]
Now it looks like the footer is too small on mobile. Looks great on desktop though!

**Comment by katanka** [comment]
LGTM

**Comment by kvas-damian** [comment]
LGTM

**Pull request merged**
