### PR TITLE
INT-269 | Google Search test: Separate tracking for intra and inter wiki search

### PR DESCRIPTION
**Pull request by mari-mcmurtrie**
Adding additional search parameter to measure intra search performance in GA. New parameter name is qIntra. We ping GA for fake page view with this new parameter.
Ticket: https://wikia-inc.atlassian.net/browse/INT-269

### CODE REVIEW

**Comment by mari-mcmurtrie** [comment]
@perjg will you CR this? Thanks!

**Comment by perjg** [comment]
LGTM

**Comment by bognix** [comment]
@mari-mcmurtrie I merged dev to your branch because there were conflicts because ES6 landed in dev.
Could you check if I resolved conflicts correctly?
Thanks!

**Comment by mari-mcmurtrie** [comment]
Awesome @bognix, thank you! I make sure it is all ok.

**Comment by mari-mcmurtrie** [comment]
I tested this. It is good.

**Pull request merged**
