### PR TITLE
HG-667 - disable logging for ember performance sender

### PR DESCRIPTION
**Pull request by katanka**

### CODE REVIEW

**Comment by lizlux** [comment]
Note that this will disable all logging, including logging on dev. IMO, this is okay since I don't see those logs as being very useful. Just pointing it out b/c the ticket specified production.

**Comment by rogatty** [comment]
Please disable it only for production, you can just use `M.prop('environment')` for that.

Logs aren't very useful in MOST situations but surely can be helpful when trying to improve performance.

**Comment by lizlux** [comment]
^ :+1:

**Comment by lizlux** [comment]
LGTM!

**Pull request merged**
