### PR TITLE
XW-456 | Remove old variations of featured content

### PR DESCRIPTION
**Pull request by vforge**
https://wikia-inc.atlassian.net/browse/XW-456

### CODE REVIEW

**Comment by Warkot** [comment]
Shouldn't `featured-content.js` component incorporate the `featured-content-variation3.js` version?

**Comment by vforge** [comment]
@Warkot Done.

**Comment by hakubo** [comment]
lgtm

**Comment by Warkot** [comment]
LGTM

**Comment by bognix** [comment]
lgtm

**Comment by Warkot** [comment]
Tests need to be fixed.

**Comment by Warkot** [comment]
LGTM

**Comment by Warkot** [comment]
Tezted. Workz. Mergin'. :shipit:

**Pull request merged**
