### PR TITLE
INT-297-2: JP homepage new design - "what is wikia" section.

### PR DESCRIPTION
**Pull request by mari-mcmurtrie**
Ticket https://wikia-inc.atlassian.net/browse/INT-297
Styled according to https://app.zeplin.io/project.html#pid=565f790bba50c0525c1eb2e2&sid=565f7ad92280bd9e5b8de3bc
Text is not yet finalized.

### CODE REVIEW

**Comment by mari-mcmurtrie** [comment]
@perjg, will you CR to see if I do right for template file and css? I hope I understand the structure right.

**Comment by perjg** [comment]
Just a minor comment, otherwise LGTM.

**Comment by mari-mcmurtrie** [comment]
@perjg I modified code more. Will you quickly CR? Thank you!

**Comment by perjg** [comment]
LGTM

**Comment by mari-mcmurtrie** [comment]
I think the error is related with node server.

**Pull request merged**
