### PR TITLE
ADEN-2406 Added detection script and event listeners to track blocking

### PR DESCRIPTION
**Pull request by fraszczakszymon**
We want to track blocking page views on Mercury, so we add existing module to dependencies and track status with existing GA methods (both profiles: ads and regular).

**Please don't merge it before ADEN-2406 app part is released.**

App PR: https://github.com/Wikia/app/pull/8627

### CODE REVIEW

**Comment by nandy-andy** [comment]
LGTM :+1:

**Comment by jacekjursza** [comment]
LGTM

**Comment by PiotrGackowski** [comment]
App part was merged - so it will be released in Thursday 1 October.

**Comment by nandy-andy** [comment]
App part was merged and today it was released. Merging the changes.

**Pull request merged**
