### PR TITLE
SOC-1576 | remove active highlighting on all links

### PR DESCRIPTION
**Pull request by katanka**
https://wikia-inc.atlassian.net/browse/SOC-1576

### CODE REVIEW

**Comment by bkoval** [comment]
@rogatty @hakubo This will remove highlighting from all the links everywhere on Mercury. We do have a green light from UX to do so on Discussions, but the question is if we can remove it everywhere. It might make sense, since these things should be consistent throughout the platform, but it appears to be more of a product decision.

If not, we'll make sure to just touch discussions with these changes for now.

**Comment by katanka** [comment]
@bkoval I confirmed with Derek Hart that it should be removed for all of Mercury.

**Comment by bkoval** [comment]
OK, perfect!

**Comment by rafalkalinski** [comment]
LGTM

**Comment by hakubo** [comment]
do we have plans to replace that with something?

**Pull request merged**
