### PR TITLE
XW-637 | add mercury 'User-Agent' and 'X-Wikia-Internal-Request' headers for all MW requests

### PR DESCRIPTION
**Pull request by Warkot**
https://wikia-inc.atlassian.net/browse/XW-637

/ping! @macbre

### CODE REVIEW

**Comment by hakubo** [comment]
You could make it in one commit you know :)

**Comment by hakubo** [comment]
LGTM

**Comment by macbre** [comment]
:+1:

**Comment by Warkot** [comment]
tested → works → merging

**Pull request merged**
