### PR TITLE
CONCF-1062 | restyled view of /main/edit

### PR DESCRIPTION
**Pull request by Warkot**

### CODE REVIEW

**Comment by Warkot** [comment]
I'm not sure if the fonts should be defined so strictly. I feel they should use some predefined values. :confused:

**Comment by rogatty** [comment]
Does it play nice with https://github.com/Wikia/mercury/pull/1248?

**Comment by Warkot** [comment]
@rogatty "Does it play nice with #1248?" — It does after the merge. :)

**Comment by bognix** [comment]
LGTM

**Comment by vforge** [comment]
LGTM

**Pull request merged**
