### PR TITLE
Authentication | Do not override userId from Helios

### PR DESCRIPTION
**Pull request by bkoval**
## Description

We should always rely on userID from Helios, not from Mediawiki. Additionally, this is causing isAuthenticated check to fail on polish devboxes, when using servicesDomain in san jose.

## Reviewers

@rogatty @vforge @rafalkalinski @Warkot

### CODE REVIEW

**Comment by rogatty** [comment]
It sucks that `UserModel` has `userId` property and that it'll always be null. This service / model hybrid needs to be cleaned anyway but maybe for now we should just set `userId` to the one that is passed to `UserModel.find()`? Or remove it from `UserModel` entirely, whatever you like better.

**Comment by hakubo** [comment]
ping @bkoval

**Comment by Warkot** [comment]
Hey, this PR is two weeks old—this slacker should be merged or closed and, after one of the aforementioned, the branch deleted to keep the repo clean. @bkoval @rafalkalinski @kvas-damian

**Comment by bkoval** [comment]
@Warkot I addressed a comment @rogatty - can you guys CR this? :)

**Comment by bkoval** [comment]
Also, should we create a ticket about cleanups in the service-model chain here?

Are there any tickets for starting to use User Attribute service instead of monolith for fetching data like username and avatar?

**Comment by rogatty** [comment]
Great question! There is no ticket that I would be aware of. IMHO it kinda looks like Social one ;)

**Comment by rogatty** [comment]
LGTM

**Comment by bkoval** [comment]
@rogatty Yep, it sounds like our job to do, just wanted to make sure we won't create a duplicate :)

**Comment by bkoval** [comment]
https://wikia-inc.atlassian.net/browse/SOC-2160

**Pull request merged**
