### PR TITLE
allow for trailing comma in ts

### PR DESCRIPTION
**Pull request by hakubo**
as per
https://github.com/Wikia/guidelines/pull/91

### CODE REVIEW

**Comment by rogatty** [comment]
LGTM

**Comment by vforge** [comment]
LGTM

**Comment by Warkot** [comment]
It's allowed, so 'you **can** use it'. Shouldn't it be more like 'you **should/have to** use it', to encourage consistency in the code?

**Comment by bkoval** [comment]
:dancingbanana:

**Comment by vforge** [comment]
@Warkot your suggestion is great and may I suggest that you open PR to Wikia/guidelines to fix it. Thanks!

**Pull request merged**
