### PR TITLE
HG-649 Don't add adsContext if it's an empty array

### PR DESCRIPTION
**Pull request by rogatty**
https://wikia-inc.atlassian.net/browse/HG-649

### CODE REVIEW

**Comment by vforge** [comment]
LGTM

**Comment by hakubo** [comment]
LGTM

**Comment by hakubo** [comment]
Ads code:
- ads slots to DOM (so we can debug it better) 
- does not load ads

**Comment by nandy-andy** [comment]
LGTM and thanks! :)

**Pull request merged**
