### PR TITLE
XW-242 Fix Curated Main Page navigation

### PR DESCRIPTION
**Pull request by rogatty**
https://wikia-inc.atlassian.net/browse/XW-242

### CODE REVIEW

**Comment by hakubo** [comment]
LgTm

**Comment by bognix** [comment]
Could you fix:
```
[1A[2KPhantomJS 1.9.8 (Linux 0.0.0) MainPageComponent reacts on curated content change FAILED
	Expected at least one assertion, but none were run - call expect(0) to accept zero assertions.
	    at /var/lib/jenkins/workspace/Mercury-Front/574/node_modules/qunitjs/qunit/qunit.js:263
	    at /var/lib/jenkins/workspace/Mercury-Front/574/www/front/vendor/sinon-qunit/lib/sinon-qunit.js:27
	    at test (/var/lib/jenkins/workspace/Mercury-Front/574/front/vendor/ember-qunit/ember-qunit.js:252)
	    at /var/lib/jenkins/workspace/Mercury-Front/574/test/specs/front/scripts/main/components/MainPageComponent.js:30

**Comment by bognix** [comment]
Fix checks. Despite that LGTM

**Comment by bognix** [comment]
LGTM

**Comment by hakubo** [comment]
B E A utiful, xoxo
LGTM

**Pull request merged**
